### ISSUE TITLE
`paper-slider` documentation opens with a description of the `change` event instead of a description of the element

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-analyzer#119] opened 2015-06-02 19:14 UTC
No idea if this problem is in the scope of this project, or another project entirely (given that this catalog sources it's data from multiple different locations), but currently the documentation for `paper-slider` has the wrong information listed in its introduction:

![paper slider polymer element catalog](https://cloud.githubusercontent.com/assets/1876931/7944080/36e254f6-092e-11e5-911f-9c17c27658b7.png)

This part which is currently listed at the top of the page is actually the documentation for the `changed` event, not a description of the element itself:

> Fired when the slider's value changes due to user interaction.
>
> Changes to the slider's value due to changes in an underlying bound variable will not trigger this event.

**Comment by garlicnation** [comment] 2015-06-04 17:54
Should be fixed by https://github.com/Polymer/hydrolysis/pull/118

**Comment by atotic** [comment] 2015-06-17 22:04
This is a paper-slider problem, still not fixed in latest. The problem is:
* jsdoc Polymer description takes precedence over dom-module description
* @event jsdoc comment is right before Polymer, and is interpreted as Polymer description.

Fix: move event descriptors somewhere else, my recommendation is after properties: inside Polymer.

**Closed** 2016-09-23 02:59 UTC
